# Generated by Django 6.0.6 on 2026-06-24 13:58

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('handle', models.SlugField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.SlugField(max_length=100, unique=True)),
                ('product_title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('handle', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('products', models.ManyToManyField(blank=True, related_name='collections', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.SlugField(max_length=100, unique=True)),
                ('variant_title', models.CharField(max_length=140)),
                ('primary_material', models.CharField(max_length=100)),
                ('secondary_material', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_color', models.CharField(max_length=100)),
                ('secondary_color', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('number_of_packages', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('stock_location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='TableAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabletop_material', models.CharField(max_length=100)),
                ('tabletop_color', models.CharField(max_length=100)),
                ('tabletop_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_attributes', to='store.variant')),
            ],
        ),
        migrations.CreateModel(
            name='SeatingAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating_material', models.CharField(max_length=100)),
                ('seating_color', models.CharField(max_length=100)),
                ('seating_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('seating_depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('seating_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('armchair_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('corner_side', models.CharField(max_length=10)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seating_attributes', to='store.variant')),
            ],
        ),
        migrations.CreateModel(
            name='LightingAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting_material', models.CharField(max_length=100)),
                ('lighting_color', models.CharField(max_length=100)),
                ('lighting_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_attributes', to='store.variant')),
            ],
        ),
        migrations.CreateModel(
            name='DecorativeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decorative_attributes', to='store.variant')),
            ],
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('display_order', models.IntegerField()),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_images', to='store.variant')),
            ],
        ),
        migrations.CreateModel(
            name='VariantShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_type', models.CharField(max_length=100)),
                ('shipping_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('package_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('package_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('package_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_shipping', to='store.variant')),
            ],
        ),
    ]
