# Generated by Django 6.0.6 on 2026-06-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_user_managers_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
