# Generated by Django 6.0.6 on 2026-06-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variant_total_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
