# Generated by Django 6.0.6 on 2026-06-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variant_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='variants', to='store.collection'),
        ),
    ]
