# Generated by Django 6.0.6 on 2026-06-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variant_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='collection',
            new_name='collections',
        ),
    ]
