# Generated by Django 6.0.6 on 2026-06-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_collection_variant_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='handle',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='handle',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
